name: Tests

on:

  # Allow workflow to be called by another workflow
  workflow_call:
    secrets:
      VITE_AUTH_URL:
        description: 'The base URL of the KAuth backend, e.g. https://global.api.konghq.tech'
        required: true
  # Allow workflow to be called manually
  workflow_dispatch:
    inputs:
      VITE_AUTH_URL:
        description: 'The base URL of the KAuth backend, e.g. https://global.api.konghq.tech'
        type: string
        default: https://global.api.konghq.tech
        required: false

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
         fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Stylelint
        run: yarn stylelint

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Run Cypress component tests
        uses: cypress-io/github-action@7ef72e250a9e564efb4ed4c2433971ada4cc38b4 # v6.10.4
        with:
          install: false
          command: yarn test
        env:
          VITE_AUTH_URL: ${{ secrets.VITE_AUTH_URL || inputs.VITE_AUTH_URL }}

      - name: Upload Cypress screenshots (on failure)
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: failure()
        with:
          name: cypress_screenshots
          path: cypress/screenshots/

      - name: Upload Cypress videos (always)
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: always()
        with:
          name: cypress_videos
          path: cypress/videos/
